import chalk from "chalk";

export default {
  appname: chalk.greenBright,
  command: chalk.magentaBright,
  date: chalk.greenBright,
  datetime: chalk.greenBright,
  dim: chalk.dim,
  fail: chalk.red,
  format: chalk,
  id: chalk.greenBright,
  important: chalk.underline.redBright,
  key: chalk.blueBright,
  number: chalk.cyan,
  option: chalk.cyan,
  param: chalk.yellowBright,
  pass: chalk.green,
  path: chalk.cyanBright,
  subcommand: chalk.magenta,
  time: chalk.greenBright,
  url: chalk.green.underline,
  value: chalk.greenBright,
  version: chalk.blueBright,
  name: chalk.greenBright,
  enum: chalk.redBright,
};
