version: 2.1

executors:
  node12:
    working_directory: /root/nd/app
    docker:
      - image: circleci/node:12
    environment:
      CI: "true"
      ENV: "ci"
      APP: /root/nd/app
      CACHE: /tmp/caches

commands:
  info:
    description: Start workflow
    steps:
      - hello/circleci-env-highlights
      - hello/system-info
  save-caches:
    description: Save node_modules and dist folder
    steps:
      - run:
          name: Create tmp folder
          command: mkdir /tmp/caches || exit 0
      - run:
          name: Move node_modules to tmp folder
          command: cp -r node_modules /tmp/caches || exit 0
      - run:
          name: Move dist to tmp folder
          command: cp -r dist /tmp/caches || exit 0
      - persist_to_workspace:
          root: /tmp
          # Must be relative path from root
          paths:
            - caches
  restore-caches:
    description: Restore dist and node_modules from tmp folder
    steps:
      - attach_workspace:
          at: /tmp/caches
      - run:
          name: Restore node_modules from tmp folder
          command: cp -r /tmp/caches/node_modules . || exit 0
      - run:
          name: Restore dist folder from tmp folder
          command: cp -r /tmp/caches/dist . || exit 0

orbs:
  hello: circleci/hello-build@0.0.14
  node: circleci/node@1.1.6
  codecov: codecov/codecov@1.0.5
  packtracker: packtracker/report@2.2.6

workflows:
  version: 2
  test:
    jobs:
      - install
      - compile:
          requires:
            - install
      - lint:
          requires:
            - compile
      - test:
          requires:
            - compile
      - codecov:
          requires:
            - test
  build:
    jobs:
      - install:
          filters:
            branches:
              only: master
      - compile-prod:
          requires:
            - install
          filters:
            branches:
              only: master
      - packtracker/report:
          requires:
            - install
          filters:
            branches:
              only: master
      - build:
          requires:
            - compile-prod
          filters:
            branches:
              only: master
      - deploy:
          type: approval
          requires:
            - build
          filters:
            branches:
              only: master

jobs:
  install:
    executor: node12
    steps:
      - checkout
      - info
      - node/with-cache:
          dir: $APP/node_modules
          steps:
            - run:
                name: Install all dependencies
                command: yarn install
      - save-caches
  compile:
    executor: node12
    steps:
      - checkout
      - restore-caches
      - run:
          name: Compile Typescript
          command: yarn compile
      - save-caches
  compile-prod:
    executor: node12
    steps:
      - checkout
      - restore-caches
      - run:
          name: Compile Typescript as Production setting
          command: yarn compile:prod
      - save-caches
  lint:
    executor: node12
    steps:
      - checkout
      - restore-caches
      - run:
          name: Run ESlint
          command: yarn helper jlint
      - store_artifacts:
          path: dist/junit/eslint.xml
          destination: report
      - store_test_results:
          path: dist/junit/eslint.xml
      - save-caches
  test:
    executor: node12
    steps:
      - checkout
      - restore-caches
      - run:
          name: Run test
          command: yarn helper jtest
      - store_artifacts:
          path: dist/junit/unittest.xml
          destination: test
      - store_artifacts:
          path: coverage
          destination: coverage
      - store_test_results:
          path: dist/junit/unittest.xml
      - save-caches
  codecov:
    executor: node12
    steps:
      - codecov/upload:
          flags: unittest
  build:
    executor: node12
    steps:
      - checkout
      - restore-caches
      - run:
          name: Build executable package
          command: yarn build
      - store_artifacts:
          path: dist
          destination: dist
      - save-caches
  deploy:
    executor: node12
    steps:
      - checkout
      - restore-caches
      - run:
          name: Run deployment script
          command: yarn release:core
