style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/kamontat/nd
options:
  commits:
    filters:
      Type:
        - feat
        - impr
        - fix
  commit_groups:
    title_maps:
      feat: 1. Introduce new features
      impr: 2. Command improvement
      fix: 3. Command bug destoryer
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  issues:
    prefix:
      - "#"
  notes:
    keywords:
      - BREAKING CHANGE
